### ISSUE TITLE
Proper display of action bar spells for (FixItemIcon)

### ISSUE THREAD

**Issue by mc2programmer** [cornernote/wow-3.3.5-addons#1]
Not sure if you are even working on this project any more, but I thought I would post this so that the Icons display correctly within the action bars as well. Just in case others attach "Auto Attack" and "Auto Shot" to the Action Bar

elseif type=="spell" then
			local spellName = GetSpellName(id, "General");
			if (spellName == "Auto Attack") then
				texture = GetInventoryItemTexture("player",16);
			elseif (spellName == "Auto Shot") then
				texture = GetInventoryItemTexture("player",18);
			end

this code should go right between lines 7 and 8

**Comment by cornernote** [comment]
These are't mine, just a collection I used to use when playing.  It took ages to get the versions from wow.curseforge.com for wow-3.3.5, so I threw them all in here.

Feel free to edit the file here on github, and it will then send me a pull request.
